### PR TITLE
Complete rewrite of everything

### LINKED ISSUE #1: Pygame window freezing
Hi! I'm currently trying to use your chessboard api with the python chess library (https://python-chess.readthedocs.io/en/latest/). Currently, my code is as follows:

```
import chess
from chessboard import display

board = chess.Board()
fen = board.fen()

while True:
     display.start(fen)
```

However, when I run the code, my pygame window freezes with a gray screen and won't display anything. I can only get out of it by exiting the program. Any tips?

### PR DESCRIPTION
**Pull request by zjeffer**
* class for the gui
* uses python-chess lib for fen parsing
* interactive: you can click pieces and move them (also checks for legality) => you can play full chessgames
* Promotion works with pygame-popup window
* dynamic tile size: set the window size at the start, the tile size will change accordingly
* fixes #1 and #4
* Added `requirements.txt` 
* Example of how to run it is in `example.py`

### CODE REVIEW

**Comment by ahira-justice** [comment]
Hello @zjeffer, I just got around to cleaning up the code tonight, after putting it off for so long. I've been able to fix #1, #2 and #4.

I've scanned over your changes, and it seems impressive. It greatly expands the scope of chess-board beyond what I originally intended.

As I stated in the README, 

"chess-board is a Python chessboard package with a flexible "just a board" API for graphically representing game positions."

I will do some work to allow input through the gui also. Thank you for the input, but I cannot merge this complete rewrite. It is too much of a departure from the original. You can of course continue to manage it on your fork.

Cheers.

PS: This fix closes #3 as it is trying to fix #2

**Comment by zjeffer** [comment]
Thanks for your response. I used this repository for my university bachelor's thesis (implementing AlphaZero in Python: https://github.com/zjeffer/chess-deep-rl) and your code was helpful to use as a base for the GUI. 

I know the changes I made are quite extensive, so I completely understand that it strays too far from the original scope of the project :)

> I will do some work to allow input through the gui also.

If you want to use parts of my code for that, you can obviously copy it into your repo. No credit necessary :)

**Comment by ahira-justice** [comment]
That's awesome! I'll read through the thesis asap.

I'm glad to know I was of some help.

**Comment by zjeffer** [comment]
> That's awesome! I'll read through the thesis asap.

The thesis itself won't be written until June, right now I just wrote the code and some info about how it works which can be found in README.md

**Comment by zjeffer** [comment]
@ahira-justice If you're still interested, you can find my thesis here: https://github.com/zjeffer/howest-thesis/blob/main/thesis.pdf

**Comment by ahira-justice** [comment]
Thank you @zjeffer

**Pull request closed without merging**
